apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: elasticsearch-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
      containers:
      - name: elasticsearch-logging
        image: elasticsearch:5.3.0-alpine
        ports:
        - containerPort: 9200
          name: es-port
          protocol: TCP
        - containerPort: 9300
          name: transport-port
          protocol: TCP
        volumeMounts:
          - name: es-persistent-storage
            mountPath: /data