apiVersion: v1
kind: Pod
metadata:
  name: fluentd
  namespace: kube-system
spec:
  containers:
  - name: fluentd
    image: fluent/fluentd:stable
    imagePullPolicy: Always
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - mountPath: /var/lib/docker/containers
      name: varlibdockercontainers
      readOnly: true
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    ports:
    - containerPort: 80
  volumes:
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: varlog
    hostPath:
      path: /var/log