apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-logging
  namespace: cl
  labels:
    k8s-app: nginx-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: nginx-logging
  template:
    metadata:
      labels:
        k8s-app: nginx-logging
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: nginx-logging
        image: nginx:1.11.13
        ports:
        - containerPort: 80
          name: nginx-port
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/sites-available
      volumes:
        - name: config
          configMap:
            name: nginxconfigmap
            items:
            - key: nginx-default
              path: default