apiVersion: v1
kind: Service
metadata:
  name: nginx-logging
  namespace: cl
  labels:
    k8s-app: nginx-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "nginx"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: nginx-port

  selector:
    k8s-app: nginx-logging
  type: LoadBalancer
